//регистрация
export const POST_REGISTER_REQUEST = 'POST_REGISTER_REQUEST'
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS'
export const POST_REGISTER_FAILED = 'POST_REGISTER_FAILED'
//логин
export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'
//обновление
export const PATCH_USER_REQUEST = 'PATCH_USER_SUCCESS';
export const PATCH_USER_SUCCESS = 'PATCH_USER_SUCCESS';
export const PATCH_USER_FAILED = 'PATCH_USER_FAILED';
//выход
export const POST_LOGOUT_REQUEST = 'POST_LOGOUT_REQUEST'
export const POST_LOGOUT_SUCCESS = 'POST_LOGOUT_SUCCESS'
export const POST_LOGOUT_FAILED = 'POST_LOGOUT_FAILED'
//токен
export const POST_TOKEN_REQUEST = 'POST_TOKEN_REQUEST'
export const POST_TOKEN_SUCCESS = 'POST_TOKEN_SUCCESS'
export const POST_TOKEN_FAILED = 'POST_TOKEN_FAILED'

export const SET_AUTH_CHECKED = "SET_AUTH_CHECKED";
export const SET_USER = 'SET_USER'